import type{AuditFinding,GeoAuditResult}from"./types";
const has=(html:string,re:RegExp)=>re.test(html);
async function fetchText(url:string){const r=await fetch(url,{redirect:"follow",headers:{"user-agent":"VALTARIQ-GEO-Audit/1.0"},signal:AbortSignal.timeout(12000)});return{ok:r.ok,status:r.status,text:await r.text(),contentType:r.headers.get("content-type")??""}}
export async function runGeoAudit(domain:string):Promise<GeoAuditResult>{const origin=domain.startsWith("http")?domain:`https://${domain}`;const home=await fetchText(origin);if(!home.ok)throw new Error(`Homepage returned HTTP ${home.status}`);const html=home.text;const checks:AuditFinding[]=[];
const add=(key:string,label:string,ok:boolean,maxScore:number,evidence:string,recommendation?:string)=>checks.push({key,label,status:ok?"pass":"fail",score:ok?maxScore:0,maxScore,evidence,recommendation});
add("title","Descriptive page title",has(html,/<title>[^<]{10,}<\/title>/i),10,"Checks whether the homepage has a meaningful HTML title.","Add a concise brand + category title.");
add("description","Meta description",has(html,/<meta[^>]+name=["']description["'][^>]+content=["'][^"']{40,}["']/i)||has(html,/<meta[^>]+content=["'][^"']{40,}["'][^>]+name=["']description["']/i),8,"Checks for a useful meta description.","Add a factual description of the company, products and market.");
add("headings","Structured headings",has(html,/<h1[\s>]/i)&&has(html,/<h2[\s>]/i),8,"Checks H1/H2 structure.","Use one clear H1 and descriptive H2 sections.");
add("schema-org","Organization schema",has(html,/"@type"\s*:\s*"(Organization|Corporation|LocalBusiness)"/i),14,"Looks for organization JSON-LD.","Publish Organization JSON-LD with canonical brand facts.");
add("schema-product","Product schema",has(html,/"@type"\s*:\s*"Product"/i),12,"Looks for Product structured data.","Add Product schema to important product pages.");
add("faq","Question-answer content",has(html,/<h[1-6][^>]*>[^<]*(what|how|why|which|can|does)[^<]*<\/h[1-6]>/i)||has(html,/"@type"\s*:\s*"FAQPage"/i),8,"Looks for explicit question-answer content.","Add buyer-focused questions with direct factual answers.");
for(const [path,key,label,points] of [["/robots.txt","robots","robots.txt accessible",10],["/sitemap.xml","sitemap","XML sitemap accessible",10],["/llms.txt","llms","llms.txt available",5]] as const){try{const r=await fetchText(new URL(path,origin).toString());add(key,label,r.ok,points,`HTTP ${r.status} at ${path}`,key==="llms"?"Consider publishing an llms.txt as an experimental machine-readable guide; do not treat it as a ranking guarantee.":`Make ${path} publicly accessible.`)}catch{add(key,label,false,points,`Could not fetch ${path}`)}}add("content","Substantial crawlable text",html.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim().length>1200,15,"Estimates whether the homepage contains substantial crawlable text.","Add specific company, product, application, proof and FAQ content.");
const score=checks.reduce((n,c)=>n+c.score,0),passed=checks.filter(c=>c.status==="pass").length,failed=checks.filter(c=>c.status==="fail").length;return{url:origin,score,findings:checks,summary:{passed,warnings:0,failed}}}
